/**
 * 技能树示例数据
 * 用于开发和测试
 */

import type { SkillTree, SkillTreeProgress, SkillTreeTemplate } from './skill-tree-types';

// 前端开发基础技能树
export const frontendBasicsTree: SkillTree = {
  id: 'frontend-basics',
  title: '前端开发基础',
  description: '从零开始学习前端开发的完整路径',
  category: 'frontend',
  difficulty: 'beginner',
  nodes: [
    {
      id: 'html-basics',
      title: 'HTML 基础',
      description: '学习 HTML5 语义化标签和基础结构',
      type: 'basic',
      status: 'completed',
      position: { x: 400, y: 50 },
      dependencies: [],
      unlocks: ['css-basics', 'html-advanced'],
      resources: [
        {
          id: 'r1',
          title: 'MDN HTML 教程',
          type: 'documentation',
          url: 'https://developer.mozilla.org/zh-CN/docs/Web/HTML',
          difficulty: 'beginner',
          completed: true,
          duration: '4 小时',
        },
        {
          id: 'r2',
          title: 'HTML 完整教程',
          type: 'video',
          url: 'https://example.com/html-course',
          difficulty: 'beginner',
          completed: true,
          duration: '3 小时',
        },
      ],
      exercises: [
        {
          id: 'e1',
          title: '创建个人简历页面',
          description: '使用语义化标签创建一个个人简历页面',
          difficulty: 'easy',
          points: 10,
          completed: true,
          attempts: 1,
          bestScore: 100,
        },
      ],
      projects: [
        {
          id: 'p1',
          title: '个人主页',
          description: '创建一个包含导航、内容区和页脚的个人主页',
          requirements: ['使用语义化标签', '包含图片和链接', '结构清晰'],
          estimatedHours: 2,
          completed: true,
          githubUrl: 'https://github.com/example/personal-page',
        },
      ],
      progress: 100,
      exp: 100,
      skillPoints: 0,
      estimatedHours: 8,
      actualHours: 7,
      notes: '已完成基础学习，掌握了常用的 HTML 标签',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-05T00:00:00Z',
      startedAt: '2026-03-01T00:00:00Z',
      completedAt: '2026-03-05T00:00:00Z',
    },
    {
      id: 'css-basics',
      title: 'CSS 基础',
      description: '掌握 CSS 样式和布局基础',
      type: 'basic',
      status: 'in_progress',
      position: { x: 250, y: 200 },
      dependencies: ['html-basics'],
      unlocks: ['css-flexbox', 'css-grid'],
      resources: [
        {
          id: 'r3',
          title: 'CSS 基础教程',
          type: 'documentation',
          url: 'https://developer.mozilla.org/zh-CN/docs/Web/CSS',
          difficulty: 'beginner',
          completed: true,
          duration: '5 小时',
        },
        {
          id: 'r4',
          title: 'CSS 选择器详解',
          type: 'article',
          url: 'https://example.com/css-selectors',
          difficulty: 'beginner',
          completed: false,
          duration: '1 小时',
        },
      ],
      exercises: [
        {
          id: 'e2',
          title: '样式化简历页面',
          description: '为之前创建的简历页面添加样式',
          difficulty: 'easy',
          points: 15,
          completed: true,
          attempts: 2,
          bestScore: 95,
        },
        {
          id: 'e3',
          title: '创建导航栏',
          description: '使用 CSS 创建一个响应式导航栏',
          difficulty: 'medium',
          points: 20,
          completed: false,
          attempts: 1,
        },
      ],
      projects: [],
      progress: 60,
      exp: 120,
      skillPoints: 0,
      estimatedHours: 12,
      notes: '正在学习 CSS 盒模型和定位',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
      startedAt: '2026-03-05T00:00:00Z',
    },
    {
      id: 'html-advanced',
      title: 'HTML 进阶',
      description: '学习表单、多媒体和 SEO 优化',
      type: 'advanced',
      status: 'available',
      position: { x: 550, y: 200 },
      dependencies: ['html-basics'],
      unlocks: ['web-accessibility'],
      resources: [
        {
          id: 'r5',
          title: 'HTML 表单完全指南',
          type: 'article',
          url: 'https://example.com/html-forms',
          difficulty: 'intermediate',
          completed: false,
          duration: '2 小时',
        },
      ],
      exercises: [],
      projects: [],
      progress: 0,
      exp: 150,
      skillPoints: 1,
      estimatedHours: 10,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
    {
      id: 'css-flexbox',
      title: 'Flexbox 布局',
      description: '掌握 Flexbox 弹性布局系统',
      type: 'advanced',
      status: 'locked',
      position: { x: 150, y: 350 },
      dependencies: ['css-basics'],
      unlocks: ['responsive-design'],
      resources: [],
      exercises: [],
      projects: [],
      progress: 0,
      exp: 150,
      skillPoints: 1,
      estimatedHours: 8,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
    {
      id: 'css-grid',
      title: 'Grid 布局',
      description: '学习 CSS Grid 网格布局',
      type: 'advanced',
      status: 'locked',
      position: { x: 350, y: 350 },
      dependencies: ['css-basics'],
      unlocks: ['responsive-design'],
      resources: [],
      exercises: [],
      projects: [],
      progress: 0,
      exp: 150,
      skillPoints: 1,
      estimatedHours: 8,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
    {
      id: 'responsive-design',
      title: '响应式设计',
      description: '创建适配多设备的响应式网页',
      type: 'expert',
      status: 'locked',
      position: { x: 250, y: 500 },
      dependencies: ['css-flexbox', 'css-grid'],
      unlocks: ['frontend-milestone'],
      resources: [],
      exercises: [],
      projects: [],
      progress: 0,
      exp: 200,
      skillPoints: 2,
      estimatedHours: 15,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
    {
      id: 'web-accessibility',
      title: 'Web 无障碍',
      description: '学习创建可访问的 Web 应用',
      type: 'advanced',
      status: 'locked',
      position: { x: 550, y: 350 },
      dependencies: ['html-advanced'],
      unlocks: ['frontend-milestone'],
      resources: [],
      exercises: [],
      projects: [],
      progress: 0,
      exp: 180,
      skillPoints: 1,
      estimatedHours: 12,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
    {
      id: 'frontend-milestone',
      title: '前端基础里程碑',
      description: '完成前端基础学习，获得认证',
      type: 'milestone',
      status: 'locked',
      position: { x: 400, y: 650 },
      dependencies: ['responsive-design', 'web-accessibility'],
      unlocks: [],
      resources: [],
      exercises: [],
      projects: [
        {
          id: 'p2',
          title: '完整的响应式网站',
          description: '创建一个包含多个页面的响应式网站',
          requirements: [
            '至少 3 个页面',
            '响应式设计',
            '无障碍支持',
            '良好的 SEO',
          ],
          estimatedHours: 20,
          completed: false,
        },
      ],
      progress: 0,
      exp: 500,
      skillPoints: 0,
      estimatedHours: 20,
      notes: '',
      documentIds: [],
      learningRecords: [],
      createdAt: '2026-03-05T00:00:00Z',
      updatedAt: '2026-03-08T00:00:00Z',
    },
  ],
  edges: [
    { id: 'e1', source: 'html-basics', target: 'css-basics', type: 'dependency' },
    { id: 'e2', source: 'html-basics', target: 'html-advanced', type: 'dependency' },
    { id: 'e3', source: 'css-basics', target: 'css-flexbox', type: 'dependency' },
    { id: 'e4', source: 'css-basics', target: 'css-grid', type: 'dependency' },
    { id: 'e5', source: 'css-flexbox', target: 'responsive-design', type: 'dependency' },
    { id: 'e6', source: 'css-grid', target: 'responsive-design', type: 'dependency' },
    { id: 'e7', source: 'html-advanced', target: 'web-accessibility', type: 'dependency' },
    { id: 'e8', source: 'responsive-design', target: 'frontend-milestone', type: 'dependency' },
    { id: 'e9', source: 'web-accessibility', target: 'frontend-milestone', type: 'dependency' },
  ],
  totalNodes: 8,
  completedNodes: 1,
  totalExp: 1550,
  earnedExp: 100,
  availableSkillPoints: 3,
  totalSkillPoints: 3,
  author: 'EduNexus',
  tags: ['前端', 'HTML', 'CSS', '基础'],
  rating: 4.8,
  enrollments: 1234,
  isPublic: true,
  isTemplate: false,
  createdAt: '2026-03-01T00:00:00Z',
  updatedAt: '2026-03-08T00:00:00Z',
};

// 学习进度
export const mockProgress: SkillTreeProgress = {
  userId: 'user-1',
  treeId: 'frontend-basics',
  completedNodes: ['html-basics'],
  inProgressNodes: ['css-basics'],
  totalExp: 100,
  skillPoints: 3,
  startedAt: '2026-03-01T00:00:00Z',
  lastActivityAt: '2026-03-08T00:00:00Z',
};

// 技能树模板
export const skillTreeTemplates: SkillTreeTemplate[] = [
  {
    id: 'frontend-fullstack',
    title: '前端开发全栈',
    description: '从零基础到全栈前端工程师的完整学习路径',
    category: 'frontend',
    preview: '/templates/frontend.png',
    nodes: [],
    edges: [],
    estimatedDuration: 240,
    difficulty: 'intermediate',
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind'],
    author: 'EduNexus Team',
    rating: 4.8,
    downloads: 15234,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'python-data-science',
    title: 'Python 数据科学',
    description: '掌握 Python 数据分析和机器学习的核心技能',
    category: 'data-science',
    preview: '/templates/python-ds.png',
    nodes: [],
    edges: [],
    estimatedDuration: 180,
    difficulty: 'intermediate',
    tags: ['Python', 'Pandas', 'NumPy', 'Scikit-learn'],
    author: 'Data Science Pro',
    rating: 4.9,
    downloads: 12890,
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'ml-beginner',
    title: '机器学习入门',
    description: '适合初学者的机器学习基础课程',
    category: 'machine-learning',
    preview: '/templates/ml.png',
    nodes: [],
    edges: [],
    estimatedDuration: 120,
    difficulty: 'beginner',
    tags: ['机器学习', 'Python', 'TensorFlow'],
    author: 'AI Academy',
    rating: 4.7,
    downloads: 9876,
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'algorithms-ds',
    title: '算法与数据结构',
    description: '系统学习常用算法和数据结构',
    category: 'algorithms',
    preview: '/templates/algo.png',
    nodes: [],
    edges: [],
    estimatedDuration: 200,
    difficulty: 'advanced',
    tags: ['算法', '数据结构', 'LeetCode'],
    author: 'Code Master',
    rating: 4.9,
    downloads: 18765,
    createdAt: '2026-01-10T00:00:00Z',
  },
];
