import { PathTemplate, PathEdge } from './path-types';

export const pathTemplates: PathTemplate[] = [
  {
    id: 'frontend-basics',
    title: '前端开发入门',
    description: '从零开始学习前端开发，掌握 HTML、CSS 和 JavaScript 基础',
    category: '前端开发',
    difficulty: 'beginner',
    estimatedDuration: 2400, // 40小时
    tags: ['HTML', 'CSS', 'JavaScript', '前端'],
    path: {
      title: '前端开发入门',
      description: '从零开始学习前端开发',
      category: '前端开发',
      difficulty: 'beginner',
      estimatedDuration: 2400,
      tags: ['HTML', 'CSS', 'JavaScript'],
      author: 'EduNexus',
      isPublic: true,
      version: 1,
      nodes: [
        {
          id: 'start',
          type: 'input',
          position: { x: 250, y: 0 },
          data: { label: '开始学习', type: 'start' as const },
        },
        {
          id: 'html-basics',
          type: 'default',
          position: { x: 250, y: 100 },
          data: {
            label: 'HTML 基础',
            description: '学习 HTML 标签、语义化和文档结构',
            type: 'document' as const,
            estimatedTime: 300,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'html-video',
          type: 'default',
          position: { x: 100, y: 200 },
          data: {
            label: 'HTML 视频教程',
            description: '观看 HTML 实战视频',
            type: 'video' as const,
            estimatedTime: 180,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'html-practice',
          type: 'default',
          position: { x: 400, y: 200 },
          data: {
            label: 'HTML 练习',
            description: '完成 HTML 编码练习',
            type: 'practice' as const,
            estimatedTime: 120,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'css-basics',
          type: 'default',
          position: { x: 250, y: 300 },
          data: {
            label: 'CSS 基础',
            description: '学习 CSS 选择器、盒模型和布局',
            type: 'document' as const,
            estimatedTime: 360,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'css-quiz',
          type: 'default',
          position: { x: 250, y: 400 },
          data: {
            label: 'CSS 测验',
            description: '测试你的 CSS 知识',
            type: 'quiz' as const,
            estimatedTime: 60,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'js-basics',
          type: 'default',
          position: { x: 250, y: 500 },
          data: {
            label: 'JavaScript 基础',
            description: '学习变量、函数和控制流',
            type: 'document' as const,
            estimatedTime: 480,
            difficulty: 'intermediate' as const,
          },
        },
        {
          id: 'js-practice',
          type: 'default',
          position: { x: 250, y: 600 },
          data: {
            label: 'JavaScript 实战',
            description: '完成 JavaScript 编程挑战',
            type: 'practice' as const,
            estimatedTime: 240,
            difficulty: 'intermediate' as const,
          },
        },
        {
          id: 'end',
          type: 'output',
          position: { x: 250, y: 700 },
          data: { label: '完成课程', type: 'end' as const },
        },
      ],
      edges: [
        { id: 'e-start-html', source: 'start', target: 'html-basics' } as PathEdge,
        { id: 'e-html-video', source: 'html-basics', target: 'html-video' } as PathEdge,
        { id: 'e-html-practice', source: 'html-basics', target: 'html-practice' } as PathEdge,
        { id: 'e-video-css', source: 'html-video', target: 'css-basics' } as PathEdge,
        { id: 'e-practice-css', source: 'html-practice', target: 'css-basics' } as PathEdge,
        { id: 'e-css-quiz', source: 'css-basics', target: 'css-quiz' } as PathEdge,
        { id: 'e-quiz-js', source: 'css-quiz', target: 'js-basics' } as PathEdge,
        { id: 'e-js-practice', source: 'js-basics', target: 'js-practice' } as PathEdge,
        { id: 'e-practice-end', source: 'js-practice', target: 'end' } as PathEdge,
      ],
    },
  },
  {
    id: 'python-basics',
    title: 'Python 编程入门',
    description: '学习 Python 基础语法和常用库',
    category: '编程语言',
    difficulty: 'beginner',
    estimatedDuration: 1800,
    tags: ['Python', '编程', '入门'],
    path: {
      title: 'Python 编程入门',
      description: '从零开始学习 Python',
      category: '编程语言',
      difficulty: 'beginner',
      estimatedDuration: 1800,
      tags: ['Python'],
      author: 'EduNexus',
      isPublic: true,
      version: 1,
      nodes: [
        {
          id: 'start',
          type: 'input',
          position: { x: 250, y: 0 },
          data: { label: '开始', type: 'start' as const },
        },
        {
          id: 'python-intro',
          type: 'default',
          position: { x: 250, y: 100 },
          data: {
            label: 'Python 简介',
            description: '了解 Python 语言特性',
            type: 'document' as const,
            estimatedTime: 120,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'python-syntax',
          type: 'default',
          position: { x: 250, y: 200 },
          data: {
            label: 'Python 语法',
            description: '学习基本语法和数据类型',
            type: 'document' as const,
            estimatedTime: 300,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'python-practice',
          type: 'default',
          position: { x: 250, y: 300 },
          data: {
            label: 'Python 练习',
            description: '编写你的第一个 Python 程序',
            type: 'practice' as const,
            estimatedTime: 180,
            difficulty: 'beginner' as const,
          },
        },
        {
          id: 'end',
          type: 'output',
          position: { x: 250, y: 400 },
          data: { label: '完成', type: 'end' as const },
        },
      ],
      edges: [
        { id: 'e1', source: 'start', target: 'python-intro' } as PathEdge,
        { id: 'e2', source: 'python-intro', target: 'python-syntax' } as PathEdge,
        { id: 'e3', source: 'python-syntax', target: 'python-practice' } as PathEdge,
        { id: 'e4', source: 'python-practice', target: 'end' } as PathEdge,
      ],
    },
  },
  {
    id: 'data-structures',
    title: '数据结构与算法',
    description: '掌握常用数据结构和算法',
    category: '计算机科学',
    difficulty: 'intermediate',
    estimatedDuration: 3600,
    tags: ['数据结构', '算法', 'LeetCode'],
    path: {
      title: '数据结构与算法',
      description: '系统学习数据结构和算法',
      category: '计算机科学',
      difficulty: 'intermediate',
      estimatedDuration: 3600,
      tags: ['数据结构', '算法'],
      author: 'EduNexus',
      isPublic: true,
      version: 1,
      nodes: [
        {
          id: 'start',
          type: 'input',
          position: { x: 250, y: 0 },
          data: { label: '开始', type: 'start' as const },
        },
        {
          id: 'array-list',
          type: 'default',
          position: { x: 250, y: 100 },
          data: {
            label: '数组与链表',
            description: '学习基础数据结构',
            type: 'document' as const,
            estimatedTime: 240,
            difficulty: 'intermediate' as const,
          },
        },
        {
          id: 'stack-queue',
          type: 'default',
          position: { x: 250, y: 200 },
          data: {
            label: '栈与队列',
            description: '理解 LIFO 和 FIFO',
            type: 'document' as const,
            estimatedTime: 180,
            difficulty: 'intermediate' as const,
          },
        },
        {
          id: 'tree-graph',
          type: 'default',
          position: { x: 250, y: 300 },
          data: {
            label: '树与图',
            description: '学习树和图的遍历',
            type: 'document' as const,
            estimatedTime: 360,
            difficulty: 'advanced' as const,
          },
        },
        {
          id: 'algorithm-practice',
          type: 'default',
          position: { x: 250, y: 400 },
          data: {
            label: '算法练习',
            description: '完成 LeetCode 题目',
            type: 'practice' as const,
            estimatedTime: 600,
            difficulty: 'advanced' as const,
          },
        },
        {
          id: 'end',
          type: 'output',
          position: { x: 250, y: 500 },
          data: { label: '完成', type: 'end' as const },
        },
      ],
      edges: [
        { id: 'e1', source: 'start', target: 'array-list' } as PathEdge,
        { id: 'e2', source: 'array-list', target: 'stack-queue' } as PathEdge,
        { id: 'e3', source: 'stack-queue', target: 'tree-graph' } as PathEdge,
        { id: 'e4', source: 'tree-graph', target: 'algorithm-practice' } as PathEdge,
        { id: 'e5', source: 'algorithm-practice', target: 'end' } as PathEdge,
      ],
    },
  },
];
